name: Auto Generate

on:
  push:
    branches:
      - main
    paths:
      - 'templates/**'
      - 'data.toml'
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate
        run: cargo run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "RBIR Bot"
          author_email: "bot@rbir.dev"
